(()=>{
'use strict';
const DATA=window.VOCAB_DATA;
if(!DATA||!Array.isArray(DATA.words)){document.body.innerHTML='<p style="color:white;padding:30px">words.js の読み込みに失敗しました。</p>';return;}
const WORDS=DATA.words;
const STORAGE='english_vocab_master_progress_v2';
const $=id=>document.getElementById(id);
const normalize=s=>String(s||'').toLowerCase().replace(/[’']/g,'').replace(/[^a-z0-9]+/g,' ').trim();
const shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
const defaultState=()=>({ratings:{},quiz:{},pron:{},unit:'ALL',mode:'card',order:'normal'});
let state=load();
let queue=[],index=0,current=null,locked=false,pronAttempts=[];
function load(){try{return {...defaultState(),...JSON.parse(localStorage.getItem(STORAGE)||'{}')}}catch{return defaultState()}}
function save(){localStorage.setItem(STORAGE,JSON.stringify(state))}
function rating(w){return Number(state.ratings[w.id]||0)}
function setRating(w,r){state.ratings[w.id]=r;save();updateStats()}
function statusLabel(r){return r===3?'習得':r===2?'あやしい':r===1?'苦手':'未判定'}
function unitWords(){if(state.mode==='weak')return WORDS.filter(w=>rating(w)<=1&&rating(w)>0);if(state.unit==='ALL')return WORDS;return WORDS.filter(w=>w.unit===state.unit)}
function buildQueue(){let a=unitWords();queue=state.order==='shuffle'?shuffle(a):[...a].sort((a,b)=>(a.unitOrder-b.unitOrder)||(a.order-b.order));index=0}
function next(){if(!queue.length){current=null;renderEmpty();return}if(index>=queue.length)index=0;current=queue[index++];renderCurrent()}
function prev(){if(!queue.length)return;index=Math.max(0,index-2);next()}
function updateStats(){const mastered=WORDS.filter(w=>rating(w)===3).length;const weak=WORDS.filter(w=>rating(w)===1).length;const tested=WORDS.filter(w=>{const q=state.quiz[w.id];return q&&(q.correct||q.wrong)}).length;$('totalCount').textContent=WORDS.length;$('masteredCount').textContent=mastered;$('weakCount').textContent=weak;$('testedCount').textContent=tested;$('dataSubtitle').textContent=`${WORDS.length}語収録・発音基準 ${DATA.pronunciationLocale||'en-US'}・データ版 ${DATA.dataVersion}`}
function initUnits(){const units=[...new Set(WORDS.map(w=>w.unit))].sort((a,b)=>{const A=WORDS.find(w=>w.unit===a)?.unitOrder||0,B=WORDS.find(w=>w.unit===b)?.unitOrder||0;return A-B});$('unitSelect').innerHTML='<option value="ALL">全単語</option>'+units.map(u=>`<option value="${esc(u)}">${esc(u)}（${WORDS.filter(w=>w.unit===u).length}語）</option>`).join('');if(!['ALL',...units].includes(state.unit))state.unit='ALL';$('unitSelect').value=state.unit;$('orderSelect').value=state.order}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function audioButtons(){return `<div class="audioRow"><button data-audio="normal">🔊 発音を聞く</button><button class="slow" data-audio="slow">🐢 ゆっくり</button></div>`}
function speak(rate=.82){if(!current||!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(current.word);u.lang='en-US';u.rate=rate;u.pitch=1;speechSynthesis.speak(u)}
function wordHeader({showWord=true,showPron=true}={}){return `<div class="prompt">${showWord?`<div class="word">${esc(current.word)}</div>`:''}${showPron?`<div class="ipa">${esc(current.ipa)}</div><div class="kana">発音ガイド：${esc(current.kanaGuide)}</div>`:''}<div class="pos">${esc(current.partOfSpeech)}</div>${showWord?audioButtons():''}</div>`}
function renderCurrent(){locked=false;pronAttempts=[];$('studyView').classList.remove('hidden');$('listView').classList.add('hidden');$('counterText').textContent=`${current.unit} ・ ${current.order} / ${WORDS.filter(w=>w.unit===current.unit).length}　｜　範囲内 ${Math.min(index,queue.length)} / ${queue.length}`;const mode=state.mode;if(mode==='card'||mode==='weak')renderCard();else if(mode==='choice')renderChoice();else if(mode==='spell')renderSpell();else if(mode==='pronounce')renderPron();$('statusLine').textContent=`現在の状態：${statusLabel(rating(current))}`;bindAudio()}
function bindAudio(){document.querySelectorAll('[data-audio]').forEach(b=>b.onclick=()=>speak(b.dataset.audio==='slow'?.58:.82))}
function renderCard(){$('promptArea').innerHTML=wordHeader();$('interactionArea').innerHTML=`<div class="interaction"><div id="cardReveal"><div class="instruction">意味を思い出してから表示してください</div><div class="actionRow"><button class="primary" id="revealBtn">意味を見る</button></div></div><div id="cardAnswer" class="hidden"><div class="meaning">${esc(current.meaning)}</div><div class="actionRow"><button class="rateBad" data-rate="1">😣 覚えてない</button><button class="rateMid" data-rate="2">🤔 あやしい</button><button class="rateGood" data-rate="3">✅ 覚えた</button></div></div><div class="actionRow"><button id="prevBtn">← 前へ</button><button id="skipBtn">次へ →</button></div></div>`;$('revealBtn').onclick=()=>{$('cardReveal').classList.add('hidden');$('cardAnswer').classList.remove('hidden')};document.querySelectorAll('[data-rate]').forEach(b=>b.onclick=()=>{setRating(current,Number(b.dataset.rate));setTimeout(next,120)});$('prevBtn').onclick=prev;$('skipBtn').onclick=next}
function meaningParts(m){return String(m||'').replace(/[〜～]/g,'').split(/[、，・／/;；]|\s+/).map(x=>x.trim()).filter(x=>x.length>=2)}
function meaningConflict(a,b){if(normalize(a.meaning)===normalize(b.meaning))return true;const A=meaningParts(a.meaning),B=meaningParts(b.meaning);return A.some(x=>B.some(y=>x===y||(x.length>=3&&y.length>=3&&(x.includes(y)||y.includes(x)))))}
function distractors(){let pool=WORDS.filter(w=>w.id!==current.id&&!meaningConflict(w,current));const samePos=shuffle(pool.filter(w=>w.partOfSpeech===current.partOfSpeech));const sameUnit=shuffle(pool.filter(w=>w.unit===current.unit&&!samePos.some(x=>x.id===w.id)));const all=shuffle(pool.filter(w=>!samePos.some(x=>x.id===w.id)&&!sameUnit.some(x=>x.id===w.id)));const out=[];for(const x of [...samePos,...sameUnit,...all]){if(!out.some(y=>normalize(y.meaning)===normalize(x.meaning)))out.push(x);if(out.length===3)break}return out}
function renderChoice(){// Critical: current.meaning is NOT inserted anywhere before the user answers.
$('promptArea').innerHTML=wordHeader();const opts=shuffle([current,...distractors()]);$('interactionArea').innerHTML=`<div class="interaction"><div class="instruction">この英単語の意味を選んでください</div><div class="options" id="choiceOptions">${opts.map(o=>`<button class="option" data-id="${o.id}">${esc(o.meaning)}</button>`).join('')}</div><div class="feedback" id="choiceFeedback"></div><div id="choiceReveal"></div></div>`;document.querySelectorAll('.option').forEach(b=>b.onclick=()=>judgeChoice(b,opts));}
function quizStat(ok){const q=state.quiz[current.id]||{correct:0,wrong:0};q[ok?'correct':'wrong']++;state.quiz[current.id]=q;let r=rating(current);if(ok)r=Math.min(3,Math.max(1,r+1));else r=1;state.ratings[current.id]=r;save();updateStats()}
function judgeChoice(btn,opts){if(locked)return;locked=true;const ok=btn.dataset.id===current.id;quizStat(ok);document.querySelectorAll('.option').forEach(b=>{b.disabled=true;if(b.dataset.id===current.id)b.classList.add('correct')});if(!ok)btn.classList.add('wrong');$('choiceFeedback').textContent=ok?'✅ 正解！':'❌ もう一度覚えよう';$('choiceReveal').innerHTML=`<div class="answerReveal"><strong>${esc(current.word)}</strong> = ${esc(current.meaning)}<br><span class="ipa">${esc(current.ipa)}</span>　<span class="kana">${esc(current.kanaGuide)}</span></div>`;setTimeout(next,1600)}
function renderSpell(){// The English spelling and pronunciation are deliberately hidden until judgment.
$('promptArea').innerHTML=`<div class="prompt"><div class="spellPrompt">${esc(current.meaning)}</div><div class="pos">${esc(current.partOfSpeech)}</div></div>`;$('interactionArea').innerHTML=`<div class="interaction"><div class="instruction">日本語から英単語を入力</div><div class="spellRow"><input id="spellInput" autocomplete="off" autocapitalize="off" spellcheck="false"><button id="spellBtn">判定</button></div><div class="feedback" id="spellFeedback"></div><div id="spellReveal"></div></div>`;const inp=$('spellInput');inp.focus();$('spellBtn').onclick=judgeSpell;inp.onkeydown=e=>{if(e.key==='Enter')judgeSpell()}}
function judgeSpell(){if(locked)return;const inp=$('spellInput');const a=normalize(inp.value);if(!a)return;locked=true;const ok=a===normalize(current.word);quizStat(ok);$('spellFeedback').textContent=ok?'✅ 正解！':`❌ 正解：${current.word}`;$('spellReveal').innerHTML=`<div class="answerReveal"><strong>${esc(current.word)}</strong><br>${esc(current.ipa)}　${esc(current.kanaGuide)}</div>`;setTimeout(next,1500)}
const SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition||null;
function editDistance(a,b){const d=Array.from({length:a.length+1},()=>Array(b.length+1).fill(0));for(let i=0;i<=a.length;i++)d[i][0]=i;for(let j=0;j<=b.length;j++)d[0][j]=j;for(let i=1;i<=a.length;i++)for(let j=1;j<=b.length;j++)d[i][j]=Math.min(d[i-1][j]+1,d[i][j-1]+1,d[i-1][j-1]+(a[i-1]===b[j-1]?0:1));return d[a.length][b.length]}
function speechGrade(text){const got=normalize(text).split(' ')[0]||'';const ans=normalize(current.word);if(got===ans)return {grade:'ok',label:'🟢 OK',got};const ratio=editDistance(got,ans)/Math.max(ans.length,1);if(got&&ratio<=.28)return {grade:'close',label:'🟡 惜しい',got};return {grade:'bad',label:'🔴 要練習',got:got||'認識なし'}}
function renderPron(){$('promptArea').innerHTML=wordHeader();$('interactionArea').innerHTML=`<div class="interaction pronBox"><div class="instruction">お手本を聞いてから1語だけ発音。最大3回で総合判定します。</div><div class="attempts" id="attempts"><div class="attempt">まだ発音していません</div></div><button class="micBtn" id="micBtn">🎤 発音してみる</button><div class="feedback" id="pronFeedback"></div><div class="note">これは「ネイティブ度」の採点ではなく、ブラウザ音声認識に英単語として通じるかの目安です。</div></div>`;const b=$('micBtn');if(!SpeechRecognition){b.disabled=true;b.textContent='このブラウザでは音声認識非対応';return}b.onclick=startRecognition}
function startRecognition(){if(pronAttempts.length>=3){pronAttempts=[];renderAttempts()}const b=$('micBtn');b.classList.add('listening');b.textContent='● 聞き取り中…';const r=new SpeechRecognition();r.lang='en-US';r.interimResults=false;r.maxAlternatives=5;let finished=false;r.onresult=e=>{finished=true;const alts=[];for(let i=0;i<e.results[0].length;i++)alts.push(e.results[0][i].transcript);let best=null;for(const t of alts){const g=speechGrade(t);if(!best||({ok:3,close:2,bad:1}[g.grade]>{ok:3,close:2,bad:1}[best.grade]))best=g}pronAttempts.push(best||speechGrade(''));renderAttempts();savePron(best);resetMic()};r.onerror=e=>{if(!finished){pronAttempts.push({grade:'bad',label:'🔴 要練習',got:`認識エラー: ${e.error}`});renderAttempts()}resetMic()};r.onend=resetMic;try{r.start()}catch{resetMic()};function resetMic(){b.classList.remove('listening');b.textContent=pronAttempts.length>=3?'🎤 3回やり直す':'🎤 発音してみる'}}
function renderAttempts(){const box=$('attempts');if(!box)return;box.innerHTML=pronAttempts.length?pronAttempts.map((a,i)=>`<div class="attempt ${a.grade}">${i+1}回目：${a.label}　認識「${esc(a.got)}」</div>`).join(''):'<div class="attempt">まだ発音していません</div>';if(pronAttempts.length>=3){const ok=pronAttempts.filter(a=>a.grade==='ok').length,close=pronAttempts.filter(a=>a.grade!=='bad').length;const result=ok>=2?'✅ 総合：発音OK':close>=2?'△ 総合：かなり近い':'🔁 総合：もう少し練習';$('pronFeedback').textContent=result}}
function savePron(g){if(!g)return;const p=state.pron[current.id]||{ok:0,close:0,bad:0};p[g.grade]=(p[g.grade]||0)+1;state.pron[current.id]=p;save()}
function renderEmpty(){$('promptArea').innerHTML='<div class="meaning">対象の単語がありません</div>';$('interactionArea').innerHTML='<div class="instruction">学習範囲またはモードを変更してください。</div>';$('counterText').textContent='';$('statusLine').textContent=''}
function setMode(m){state.mode=m;save();document.querySelectorAll('#modeNav button').forEach(b=>b.classList.toggle('active',b.dataset.mode===m));if(m==='list'){renderList();return}$('listView').classList.add('hidden');$('studyView').classList.remove('hidden');buildQueue();next()}
function renderList(){state.mode='list';save();$('studyView').classList.add('hidden');$('listView').classList.remove('hidden');renderTable()}
function renderTable(){const q=normalize($('searchInput').value);const base=state.unit==='ALL'?WORDS:WORDS.filter(w=>w.unit===state.unit);const rows=base.filter(w=>!q||normalize(`${w.word} ${w.meaning} ${w.partOfSpeech} ${w.kanaGuide}`).includes(q));$('listCount').textContent=`${rows.length}語`;$('wordTable').innerHTML=rows.map(w=>`<tr><td><strong>${esc(w.word)}</strong></td><td>${esc(w.ipa)}</td><td>${esc(w.kanaGuide)}</td><td>${esc(w.meaning)}</td><td>${esc(w.partOfSpeech)}</td><td class="state${rating(w)}">${statusLabel(rating(w))}</td></tr>`).join('')}
function exportProgress(){const blob=new Blob([JSON.stringify({schema:2,exportedAt:new Date().toISOString(),state},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='english_vocab_progress.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function importProgress(file){const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);state={...defaultState(),...(x.state||x)};save();updateStats();initUnits();setMode(state.mode==='list'?'card':state.mode);alert('進捗を読み込みました。')}catch{alert('進捗ファイルを読み込めませんでした。')}};r.readAsText(file)}
// events
$('modeNav').onclick=e=>{const b=e.target.closest('button[data-mode]');if(b)setMode(b.dataset.mode)};
$('unitSelect').onchange=e=>{state.unit=e.target.value;save();if(state.mode==='list')renderTable();else{buildQueue();next()}};
$('orderSelect').onchange=e=>{state.order=e.target.value;save();if(state.mode!=='list'){buildQueue();next()}};
$('searchInput').oninput=renderTable;
$('settingsBtn').onclick=()=>$('dataDialog').showModal();
$('exportBtn').onclick=exportProgress;
$('importInput').onchange=e=>{if(e.target.files[0])importProgress(e.target.files[0])};
$('resetBtn').onclick=()=>{if(confirm('学習履歴をすべてリセットしますか？')){state=defaultState();save();updateStats();initUnits();setMode('card');$('dataDialog').close()}};
initUnits();updateStats();setMode(state.mode||'card');
})();
